// AUTO-GENERATED by cronify. Do not edit — run `cronify generate` to regenerate.
import job from "../../../../../cron/cleanup-old-sessions";
import { createRouteHandler } from "cronify/server";

export const { GET, POST } = createRouteHandler(job);
